import type { Metadata } from 'next';
import { Geist, Geist_Mono, Playfair_Display, Outfit, Inter } from 'next/font/google';

import TanstackQueryLayout from '@/layouts/TanstackQueryLayout';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
});

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${outfit.variable} ${inter.variable} font-inter antialiased`}
      >
        <TanstackQueryLayout>{children}</TanstackQueryLayout>
      </body>
    </html>
  );
}
